const AUTH = {
  SIGN_UP: 'AUTH_SIGN_UP',
  SIGN_IN: 'AUTH_SIGN_IN',
  SIGN_UP_SUCCESS: 'AUTH_SIGN_UP_SUCCESS',
  SIGN_IN_SUCCESS: 'AUTH_SIGN_IN_SUCCESS',
  LOAD_USER: 'AUTH_LOAD_USER',
  FAIL: 'AUTH_FAIL',
  RESET_ERROR: 'AUTH_RESET_ERROR',
};

export { AUTH };
