const AUTH = {
  SIGN_UP: 'AUTH_SIGN_UP',
  SIGN_IN: 'AUTH_SIGN_IN',
  SIGN_UP_SUCCESS: 'AUTH_SIGN_UP_SUCCESS',
  SIGN_IN_SUCCESS: 'AUTH_SIGN_IN_SUCCESS',
  AUTH_FAIL: 'AUTH_AUTH_FAIL',
};

export { AUTH };
